/// Generated by AssetsRefGenerator on 2020/05/18
class Res {
  static const String background = "images/background.png";
  static const String nfcap = "images/nfcap.png";
  static const String profilepic = "images/profilepic.png";
  static const String splash = "images/splash.png";
}
